package GUI.Usuario;

import interfaz.UpdateListener;
import com.mycompany.mutuales.DataBase;
import com.mycompany.mutuales.Usuario;
import com.mycompany.mutuales.Utilidades;
import enumeradores.RolUsuario;
import static interfaz.iCargaImagenes.url_imagen_rigth;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

public class FormCrearUsuario extends javax.swing.JFrame {

    boolean esPrimerIngreso = true;
    boolean esPrimerIngresopass2 = true;

    private UpdateListener update;

    public FormCrearUsuario() {
        initComponents();
        configComponents();
        cargarImagenes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JPanel jPanel3 = new javax.swing.JPanel();
        javax.swing.JPanel jPanel4 = new javax.swing.JPanel();
        CrearUsuarioButton = new javax.swing.JLabel();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        javax.swing.JPanel jPanel5 = new javax.swing.JPanel();
        jPasswordField = new javax.swing.JPasswordField();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        confirmacionjPasswordField = new javax.swing.JPasswordField();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();
        AdvertenciaUsuario = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        AdvertenciaContraseñ = new javax.swing.JLabel();
        NombrejTextField = new javax.swing.JTextField();
        IsAdminjCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(252, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(252, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(252, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CrearUsuarioButton.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        CrearUsuarioButton.setForeground(new java.awt.Color(102, 102, 102));
        CrearUsuarioButton.setText("Crear Usuario");
        CrearUsuarioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearUsuarioButtonMouseClicked(evt);
            }
        });
        jPanel4.add(CrearUsuarioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 120, 40));

        jLabel8.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Contraseña:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        jPanel5.setBackground(new java.awt.Color(0, 153, 204));
        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 540, -1));

        jPasswordField.setText("jPasswordField1");
        jPasswordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordFieldMouseClicked(evt);
            }
        });
        jPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordFieldKeyTyped(evt);
            }
        });
        jPanel4.add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 140, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Contraseña:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, 10));

        confirmacionjPasswordField.setText("jPasswordField1");
        confirmacionjPasswordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmacionjPasswordFieldMouseClicked(evt);
            }
        });
        confirmacionjPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                confirmacionjPasswordFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                confirmacionjPasswordFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                confirmacionjPasswordFieldKeyTyped(evt);
            }
        });
        jPanel4.add(confirmacionjPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 140, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("de usuario:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Confirme");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 207, -1, 10));

        jLabel9.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Nombre");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 117, -1, -1));

        AdvertenciaUsuario.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        AdvertenciaUsuario.setForeground(new java.awt.Color(255, 102, 102));
        AdvertenciaUsuario.setText("El nombre de Usuario ya existe.");
        jPanel4.add(AdvertenciaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 143, 180, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 204));
        jLabel3.setText("Creacion de Usuario ");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        AdvertenciaContraseñ.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        AdvertenciaContraseñ.setForeground(new java.awt.Color(255, 102, 102));
        AdvertenciaContraseñ.setText("Las contraseñas no coinciden.");
        jPanel4.add(AdvertenciaContraseñ, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 233, 180, -1));
        jPanel4.add(NombrejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 140, -1));

        IsAdminjCheckBox.setText("Es administrador");
        IsAdminjCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IsAdminjCheckBoxActionPerformed(evt);
            }
        });
        jPanel4.add(IsAdminjCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 250, 230, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 380));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 380));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CrearUsuarioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearUsuarioButtonMouseClicked
        if (!camposVacios()) {
            Boolean Verificacion = true;
            if (!contraseñaSonIgules()) {
                AdvertenciaContraseñ.setVisible(true);
                Verificacion = false;
            } else {
                AdvertenciaContraseñ.setVisible(false);
            }

            if (NombreUsuarioExiste(NombrejTextField.getText().toString())) {
                AdvertenciaUsuario.setVisible(true);
                Verificacion = false;
            } else {
                AdvertenciaUsuario.setVisible(false);
            }

            if (Verificacion) {
                AdvertenciaUsuario.setVisible(false);
                AdvertenciaContraseñ.setVisible(false);
                String nombre = NombrejTextField.getText().toString();
                String contrasenia = jPasswordField.getText().toString();
                Usuario user ;
                if (IsAdminjCheckBox.isSelected()) {
                     user = new Usuario(nombre, contrasenia, RolUsuario.administrador);
                } else {
                     user = new Usuario(nombre, contrasenia);
                }
                user.insertarEnBaseDeDatos();
                limpiarCampos();
                update.updateTableData();

            }
        } else {
            Utilidades.mensajeAdvertencia("Complete los campos.");
        }
    }

    private boolean contraseñaSonIgules() {
        return jPasswordField.getText().toString().equals(confirmacionjPasswordField.getText().toString());

    }//GEN-LAST:event_CrearUsuarioButtonMouseClicked

    private void jPasswordFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldKeyTyped
        if (esPrimerIngreso) {
            jPasswordField.setText("");
            esPrimerIngreso = false;
        }
    }//GEN-LAST:event_jPasswordFieldKeyTyped

    private void confirmacionjPasswordFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmacionjPasswordFieldKeyTyped
        // TODO add your handling code here:
        if (esPrimerIngresopass2) {
            confirmacionjPasswordField.setText("");
            esPrimerIngreso = false;
        }

    }//GEN-LAST:event_confirmacionjPasswordFieldKeyTyped

    private void jPasswordFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordFieldMouseClicked
        // TODO add your handling code here:
        if (esPrimerIngreso) {
            jPasswordField.setText("");
            esPrimerIngreso = false;
        }
    }//GEN-LAST:event_jPasswordFieldMouseClicked

    private void confirmacionjPasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmacionjPasswordFieldKeyPressed
        // TODO add your handling code here:
        if (esPrimerIngresopass2) {
            confirmacionjPasswordField.setText("");
            esPrimerIngresopass2 = false;
        }
    }//GEN-LAST:event_confirmacionjPasswordFieldKeyPressed

    private void confirmacionjPasswordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmacionjPasswordFieldKeyReleased
        // TODO add your handling code here:
        if (esPrimerIngresopass2) {
            confirmacionjPasswordField.setText("");
            esPrimerIngresopass2 = false;
        }
    }//GEN-LAST:event_confirmacionjPasswordFieldKeyReleased

    private void jPasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldKeyPressed
        // TODO add your handling code here:
        if (esPrimerIngreso) {
            jPasswordField.setText("");
            esPrimerIngreso = false;
        }
    }//GEN-LAST:event_jPasswordFieldKeyPressed

    private void confirmacionjPasswordFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmacionjPasswordFieldMouseClicked
        // TODO add your handling code here:
        if (esPrimerIngresopass2) {
            confirmacionjPasswordField.setText("");
            esPrimerIngresopass2 = false;
        }
    }//GEN-LAST:event_confirmacionjPasswordFieldMouseClicked

    private void IsAdminjCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IsAdminjCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IsAdminjCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JLabel AdvertenciaContraseñ;
    javax.swing.JLabel AdvertenciaUsuario;
    javax.swing.JLabel CrearUsuarioButton;
    javax.swing.JCheckBox IsAdminjCheckBox;
    javax.swing.JTextField NombrejTextField;
    javax.swing.JPasswordField confirmacionjPasswordField;
    javax.swing.JPasswordField jPasswordField;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {
        NombrejTextField.setText("");
        jPasswordField.setText("");
        confirmacionjPasswordField.setText("");
    }

    private boolean NombreUsuarioExiste(String userName) {

        try {
            return DataBase.getInstance(true).consulta("SELECT * FROM usuario WHERE username = '" + userName + "'").next();
        } catch (SQLException ex) {
            Logger.getLogger(FormCrearUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;

    }

    private void configComponents() {
        AdvertenciaContraseñ.setVisible(false);
        AdvertenciaUsuario.setVisible(false);
    }

    private boolean camposVacios() {
        return NombrejTextField.getText().isEmpty() || confirmacionjPasswordField.getText().isEmpty() || jPasswordField.getText().isEmpty();
    }

    public void addListener(UpdateListener update) {
        this.update = update;
    }

    private void cargarImagenes() {
        String dirActual = System.getProperty("user.dir");
        CrearUsuarioButton.setIcon(new javax.swing.ImageIcon(dirActual + url_imagen_rigth));
        try {
            BufferedImage iconImage = ImageIO.read(new File(dirActual + "\\images\\icono.png"));

            // Establecer la imagen como ícono de la aplicación
            this.setIconImage(iconImage);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
