package GUI.Mutual;

import interfaz.UpdateListener;
import com.mycompany.mutuales.Mutual;
import com.mycompany.mutuales.Utilidades;
import static interfaz.iCargaImagenes.url_imagen_rigth;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

public class ModificarMutual extends javax.swing.JFrame {

    private UpdateListener update;
    private Mutual mutual;

    public ModificarMutual(Mutual mutual, UpdateListener update) {
        try {

            this.mutual = mutual;
            this.update = update;

            initComponents();
            cargarImagenes();
            cargarDatos();
        } catch (SQLException ex) {
            Logger.getLogger(ModificarMutual.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JPanel jPanel3 = new javax.swing.JPanel();
        ModificarButton = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        NombrejTextField = new javax.swing.JTextField();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(252, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(252, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ModificarButton.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        ModificarButton.setForeground(new java.awt.Color(102, 102, 102));
        ModificarButton.setText("Modificar");
        ModificarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModificarButtonMouseClicked(evt);
            }
        });
        jPanel3.add(ModificarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 130, 40));

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("MODIFICACION MUTUAL DE MUTUAL");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));
        jPanel3.add(NombrejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 110, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Nombre");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 540, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 300));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ModificarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificarButtonMouseClicked

        if (!NombrejTextField.getText().isEmpty()) {

            try {

                this.mutual.setNombre(NombrejTextField.getText());

                if (!this.mutual.existeMutual()) {
                    if (Utilidades.mensajeConfirmar("¿Desea confirmar la modificación?", "Confirmar modificación")) {

                        this.mutual.modificarMutualActiva(NombrejTextField.getText());
                        update.updateTableData();
                        this.dispose();
                        Utilidades.mensajeExito("Mutual modificada con exito!.");
                    }
                } else {
                    Utilidades.mensajeError("Ya existe otra mutual con ese nombre.");
                }
            } catch (SQLException ex) {
                Logger.getLogger(ModificarMutual.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            Utilidades.mensajeAdvertencia("El nombre no puede estar vacío.");
        }
    }//GEN-LAST:event_ModificarButtonMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JLabel ModificarButton;
    javax.swing.JTextField NombrejTextField;
    // End of variables declaration//GEN-END:variables

    private void cargarDatos() throws SQLException {
//        IdMutualTextField1.setText(String.valueOf(mutual.getId()));
//        DescripcionjTextField.setText(mutual.getDescripcion());
    }

    private void cargarImagenes() {
        String dirActual = System.getProperty("user.dir");
        ModificarButton.setIcon(new javax.swing.ImageIcon(dirActual + url_imagen_rigth));
        NombrejTextField.setText(this.mutual.getNombre());
        try {
            BufferedImage iconImage = ImageIO.read(new File(dirActual + "\\images\\icono.png"));

            // Establecer la imagen como ícono de la aplicación
            this.setIconImage(iconImage);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
