package GUI.Complementaria;

import GUI.Mutual.FormAltaMutual;
import com.mycompany.mutuales.InfoComplementaria;
import com.mycompany.mutuales.Utilidades;
import enumeradores.TipoMutual;
import interfaz.iCargaImagenes;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

public class FormAltaComplementaria extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    private InfoComplementaria info;
    private FormAltaMutual formPrincipal;

    public FormAltaComplementaria(InfoComplementaria info, FormAltaMutual formPrincipal) {
        this.info = info;
        this.formPrincipal = formPrincipal;
        initComponents();
        cargarComponentes();
        cargarImagenes();

        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                cerrarVentana();
            }
        });
    }

    private void cerrarVentana() {

        if (!OrigenjTextField.getText().isEmpty()) {
            info.setOrigen(Utilidades.agregarExtensionTxt(OrigenjTextField.getText()));
        }

        if (!DestinojTextField.getText().isEmpty()) {
            info.setDestino(Utilidades.agregarExtensionTxt(DestinojTextField.getText()));
        }

        if (!Concepto1jTextField.getText().isEmpty()) {
            info.setConcep1(Utilidades.validarYConvertirAEntero(Concepto1jTextField.getText()));
        }

        if (!Concepto2jTextField.getText().isEmpty()) {
            info.setConcep2(Utilidades.validarYConvertirAEntero(Concepto2jTextField.getText()));
        }

        formPrincipal.habilitarFormulariosReclamo();
        formPrincipal.habilitarFormulariosPrestamos();

        formPrincipal.actualizarInformacion(info);

        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        AltaButton = new javax.swing.JLabel();
        tituloJlabel = new javax.swing.JLabel();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        OrigenjTextField = new javax.swing.JTextField();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        DestinojTextField = new javax.swing.JTextField();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        Concepto1jTextField = new javax.swing.JTextField();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        Concepto2jTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(252, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(252, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AltaButton.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        AltaButton.setForeground(new java.awt.Color(102, 102, 102));
        AltaButton.setText("Guardar");
        AltaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AltaButtonMouseClicked(evt);
            }
        });
        jPanel3.add(AltaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 110, 40));

        tituloJlabel.setBackground(new java.awt.Color(51, 51, 51));
        tituloJlabel.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        tituloJlabel.setForeground(new java.awt.Color(102, 102, 102));
        tituloJlabel.setText("Informacion de adicional ");
        jPanel3.add(tituloJlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 520, 20));

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Origen");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));
        jPanel3.add(OrigenjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 110, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Destino");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));
        jPanel3.add(DestinojTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 110, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Concepto 1");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        Concepto1jTextField.setScrollOffset(-1);

       
        Concepto1jTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Concepto1jTextFieldKeyTyped(evt);
            }
        });

        jPanel3.add(Concepto1jTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 110, -1));

        jLabel8.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Concepto 2");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

       
        Concepto2jTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Concepto2jTextFieldKeyTyped(evt);
            }
        });
        jPanel3.add(Concepto2jTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 110, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 420));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AltaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AltaButtonMouseClicked

        if (Utilidades.validarCampos(OrigenjTextField, DestinojTextField, Concepto1jTextField, Concepto2jTextField)) {
            // Validar que Concepto1jTextField y Concepto2jTextField sean numéricos

            info.setOrigen(Utilidades.agregarExtensionTxt(OrigenjTextField.getText()));
            info.setDestino(Utilidades.agregarExtensionTxt(DestinojTextField.getText()));

            info.setConcep1(Utilidades.validarYConvertirAEntero(Concepto1jTextField.getText()));
            info.setConcep2(Utilidades.validarYConvertirAEntero(Concepto2jTextField.getText()));

            formPrincipal.actualizarInformacion(info);
            if (this.info.getTipoMutual() == TipoMutual.A) {

                formPrincipal.setSeGuardoPrestamo(true);
                formPrincipal.habilitarComponentes(TipoMutual.A);
            } else {
                formPrincipal.setSeGuardoReclamo(true);
                formPrincipal.habilitarComponentes(TipoMutual.R);
            }

            this.dispose();

        } else {
            Utilidades.mensajeAdvertencia("Debe completar el formulario");
        }
    }//GEN-LAST:event_AltaButtonMouseClicked


    private void Concepto1jTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Concepto1jTextFieldKeyTyped
        // TODO add your handling code here:
        char teclaPulsada = evt.getKeyChar(); // Recogemos, a partir del evento, la tecla que se pulsó

        if (!Character.isDigit(teclaPulsada)) { // Si la tecla pulsada no es un dígito, entonces...
            evt.consume(); // Borramos la última letra introducida (lo hace muy rápido, la
            // letra nunca se escribe en el textfield)
        }

    }//GEN-LAST:event_Concepto1jTextFieldKeyTyped

    private void Concepto2jTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Concepto2jTextFieldKeyTyped
        // TODO add your handling code here:
        char teclaPulsada = evt.getKeyChar(); // Recogemos, a partir del evento, la tecla que se pulsó

        if (!Character.isDigit(teclaPulsada)) { // Si la tecla pulsada no es un dígito, entonces...
            evt.consume(); // Borramos la última letra introducida (lo hace muy rápido, la
            // letra nunca se escribe en el textfield)
        }
    }//GEN-LAST:event_Concepto2jTextFieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JLabel AltaButton;
    javax.swing.JTextField Concepto1jTextField;
    javax.swing.JTextField Concepto2jTextField;
    javax.swing.JTextField DestinojTextField;
    javax.swing.JTextField OrigenjTextField;
    javax.swing.JPanel jPanel3;
    javax.swing.JLabel tituloJlabel;
    // End of variables declaration//GEN-END:variables

    private void cargarComponentes() {
        tituloJlabel.setText(tituloJlabel.getText()
                + Utilidades.obtenerTipoMutual_str(this.info.getTipoMutual()));
    }

    private void cargarImagenes() {
        String dirActual = System.getProperty("user.dir");
        AltaButton.setIcon(new javax.swing.ImageIcon(dirActual + iCargaImagenes.url_imagen_rigth));
        try {
            BufferedImage iconImage = ImageIO.read(new File(dirActual + "\\images\\icono.png"));

            // Establecer la imagen como ícono de la aplicación
            this.setIconImage(iconImage);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public void mostrarValores(InfoComplementaria info) {
        // Establecer valores en los campos del formulario
        OrigenjTextField.setText(info.getOrigen());
        DestinojTextField.setText(info.getDestino());
        Concepto1jTextField.setText(String.valueOf(info.getConcep1()));
        Concepto2jTextField.setText(String.valueOf(info.getConcep2()));
    }
}
