package GUI;

import com.mycompany.mutuales.Session;
import com.mycompany.mutuales.DataBase;
import enumeradores.RolUsuario;
import com.mycompany.mutuales.Usuario;
import com.mycompany.mutuales.Utilidades;

import static interfaz.IConsultaSql.consulta_autenticacion;
import static interfaz.iCargaImagenes.url_imagen_login;
import static interfaz.iCargaImagenes.url_imagen_rigth;

import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.imageio.ImageIO;

import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author dgc06
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    boolean esPrimerIngreso = true;

    public LoginForm() {
        initComponents();
        cargarImagenes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        iconoLoginLabel = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        UsuriojTextField = new javax.swing.JTextField();
        IiniciarSesionbutton = new javax.swing.JLabel();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(252, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(iconoLoginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 140, 150));

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel3.setText("USUARIO:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyTyped(evt);
            }
        });
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 110, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel4.setText("CONTRASEÑA:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));
        jPanel1.add(UsuriojTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 110, -1));

        IiniciarSesionbutton.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        IiniciarSesionbutton.setText(" Iniciar Session");
        IiniciarSesionbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IiniciarSesionbuttonMouseClicked(evt);
            }
        });
        jPanel1.add(IiniciarSesionbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 130, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 490));

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 540, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void IiniciarSesionbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IiniciarSesionbuttonMouseClicked
        autenticarUsuario();
    }//GEN-LAST:event_IiniciarSesionbuttonMouseClicked

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            autenticarUsuario();
        }
       
        // TODO add your handling code here:

    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked
        // TODO add your handling code here:
        if (esPrimerIngreso) {
            jPasswordField1.setText("");
            esPrimerIngreso = false;
        }
    }//GEN-LAST:event_jPasswordField1MouseClicked

    private void jPasswordField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyTyped
        // TODO add your handling code here:
        if (esPrimerIngreso) {
            jPasswordField1.setText("");
            esPrimerIngreso = false;
        }
    }//GEN-LAST:event_jPasswordField1KeyTyped

    private void autenticarUsuario() {
        try {
            Usuario user = new Usuario(UsuriojTextField.getText(), jPasswordField1.getText());
            PreparedStatement pstmt = DataBase.getInstance(true).getPreparedStatement(consulta_autenticacion);
            pstmt.setString(1, user.getNombre());
            ResultSet resultSet = pstmt.executeQuery();

            if (resultSet.next()) {
                String hashedClave = resultSet.getString("clave");
                boolean esAdmin = resultSet.getBoolean("es_administrador");
                // Verifica la clave con BCrypt
                boolean autenticado = BCrypt.checkpw(user.getContasenia(), hashedClave);

                if (autenticado && esAdmin) {
                    System.out.println("Inicio de sesión exitoso como administrador");
                    System.out.println("usuario valido");
                    boolean isAdmin = true;
                    Session permiso = new Session(UsuriojTextField.getText(), RolUsuario.administrador);
                    new MenuBienvenida().setVisible(true);
                    this.dispose();
                } else if (autenticado) {
                    System.out.println("Inicio de sesión exitoso como usuario nomal");
                    System.out.println("usuario valido");
                    boolean isAdmin = false;
                    Session permiso = new Session(UsuriojTextField.getText(), RolUsuario.usuarioSimple);
                    new MenuBienvenida().setVisible(true);
                    this.dispose();
                } else {
                    Utilidades.mensajeError("Usuario y/o contraseña incorrecto");
                }
                pstmt.close();
            }  else {
                    Utilidades.mensajeError("Usuario y/o contraseña incorrecto");
                }
        } catch (SQLException ex) {
            Utilidades.mensajeError("Error al autenticar el usuario");
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JLabel IiniciarSesionbutton;
    javax.swing.JTextField UsuriojTextField;
    javax.swing.JLabel iconoLoginLabel;
    javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables

    private void cargarImagenes() {
        String dirActual = System.getProperty("user.dir");
        iconoLoginLabel.setIcon(new javax.swing.ImageIcon(dirActual + url_imagen_login));
        IiniciarSesionbutton.setIcon(new javax.swing.ImageIcon(dirActual + url_imagen_rigth));
        try {
            BufferedImage iconImage = ImageIO.read(new File(dirActual + "\\images\\icono.png"));

            // Establecer la imagen como ícono de la aplicación
            this.setIconImage(iconImage);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

}
