package GUI;

import static interfaz.iCargaImagenes.url_imagen_fileN;
import static interfaz.iCargaImagenes.url_imagen_informe;
import static interfaz.iCargaImagenes.url_imagen_setting;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

public class MenuBienvenida extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    public MenuBienvenida() {
        initComponents();
        cargarImagenes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        fondoIconLabel = new javax.swing.JLabel();
        javax.swing.JLabel jLabel11 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel12 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        configjLabel10 = new javax.swing.JLabel();
        informeLabel = new javax.swing.JLabel();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel13 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 204));
        jLabel2.setText("Sistema de Mutuales");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 240, 30));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 204));
        jLabel6.setText("Prestamos y reclamos");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 250, -1));

        fondoIconLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\dgc06\\Documents\\nuevo repo\\mutuales\\images\\fiileN.png")); // NOI18N
        fondoIconLabel.setRequestFocusEnabled(false);
        fondoIconLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fondoIconLabelMouseClicked(evt);
            }
        });
        jPanel2.add(fondoIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, -1, -1));

        jLabel11.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 204));
        jLabel11.setText("Controlar ");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, -1));

        jLabel12.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Seleccione su Gestion:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 204));
        jLabel3.setText("Reportes");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, -1, -1));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setText("Prestamos y Reclamos");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        configjLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\dgc06\\Documents\\nuevo repo\\mutuales\\images\\setting.png")); // NOI18N
        configjLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                configjLabel10MouseClicked(evt);
            }
        });
        jPanel2.add(configjLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 530, -1, -1));

        informeLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\dgc06\\Documents\\nuevo repo\\mutuales\\images\\informe-seo.png")); // NOI18N
        informeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                informeLabelMouseClicked(evt);
            }
        });
        jPanel2.add(informeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 243, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\dgc06\\Documents\\nuevo repo\\mutuales\\images\\circulo azul.png")); // NOI18N
        jLabel8.setEnabled(false);
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 216, 70, 130));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\dgc06\\Documents\\nuevo repo\\mutuales\\images\\circulo azul.png")); // NOI18N
        jLabel13.setEnabled(false);
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 70, 130));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 590));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void configjLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configjLabel10MouseClicked
        // TODO add your handling code here:
        new ConfiguracionSistema().setVisible(true);
    }//GEN-LAST:event_configjLabel10MouseClicked

    private void fondoIconLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fondoIconLabelMouseClicked

        try {
            new FormPrincipal().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MenuBienvenida.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_fondoIconLabelMouseClicked

    private void informeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_informeLabelMouseClicked
        try {
            // TODO add your handling code here:
            new InformesForm().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MenuBienvenida.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_informeLabelMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JLabel configjLabel10;
    javax.swing.JLabel fondoIconLabel;
    javax.swing.JLabel informeLabel;
    // End of variables declaration//GEN-END:variables

    private void cargarImagenes() {
        String dirActual = System.getProperty("user.dir");

        informeLabel.setIcon(new javax.swing.ImageIcon(dirActual + url_imagen_informe ));
        fondoIconLabel.setIcon(new javax.swing.ImageIcon(dirActual + url_imagen_fileN));
        configjLabel10.setIcon(new javax.swing.ImageIcon(dirActual + url_imagen_setting));
        try {
            BufferedImage iconImage = ImageIO.read(new File(dirActual+"\\images\\icono.png"));
            
            // Establecer la imagen como ícono de la aplicación
            this.setIconImage(iconImage);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

}
